AWSTemplateFormatVersion: '2010-09-09'
Description: >
  This creates the API gateway for our Lambda function. The requirements
  state that this API Gateway must have 2 stages.

Resources:
  ApiGateway:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Description: API Gateway for our serverless application
      Name: PeterOnicaTestApiGateway

  ApiUsersResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !GetAtt ApiGateway.RootResourceId
      PathPart: users
      RestApiId: !Ref ApiGateway

  ApiGetAllMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      ApiKeyRequired: false
      AuthorizationType: NONE
      HttpMethod: GET
      Integration:
        IntegrationHttpMethod: POST
        Type: "AWS_PROXY"
        Uri: !Sub
          - "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${lambdaArn}/invocations"
          - lambdaArn:
              Fn::ImportValue:
                'PeterOnicaTestLambdaARN'
      ResourceId: !Ref ApiUsersResource
      RestApiId: !Ref ApiGateway

  ApiGatewayDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      - ApiGetAllMethod
    Properties:
      RestApiId: !Ref ApiGateway
      StageName: dev
