AWSTemplateFormatVersion: '2010-09-09'
Description: >
  This template creates the DynamoDB table, all its relevant resources
  and outputs the table's name. The table would have no provisioned capacity
  and would be set to on-demand mode


Resources:
  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        -
          AttributeName: id
          AttributeType: S
      KeySchema:
        -
          AttributeName: id
          KeyType: HASH

Outputs:
  TableName:
    Value: !Ref 'DynamoDBTable'
    Description: >
      Since no name was provided to the DynamoDB table resource, AWS will choose a
      random name for it, so we need to export that.
    Export:
      Name: DynamoDBTableName

